### ISSUE TITLE
Question: Save to log file

### ISSUE THREAD

**Issue by anoop4real** [apple/swift-log#101]
Just a question, can I get the logs written to a log file locally with in the App directory?

**Comment by ktoso** [comment]
Hi there,
I see you closed the ticket already but quick answer for context;

So this package and its implementations is more designed for server side, and by itself it does not log anywhere. For any questions about how/where things actually get logged to files refer to implementations: https://github.com/apple/swift-log#selecting-a-logging-backend-implementation-applications-only

Hope this helps,
