### ISSUE TITLE
Why docs don't mention iOS?

### ISSUE THREAD

**Issue by massdonati** [apple/swift-log#116]
Hello!
I noticed that the framework can be used in iOS, from closed issues and from the fact that I was able to add the package in Xcode. Should the README be updated to reflect this functionality? Do other features need to be implemented before updating it?

**Comment by ravikandhadai** [comment]
@massdonati If you are interested in iOS and also more generally in Apple platforms, you may want to look at the [os_log and the unified logging system](https://developer.apple.com/documentation/os/logging). 

The unified logging system is much more optimized to log on Apple devices. Note that using os_log through swift-log (using some of the backends mentioned in the README file), will *not* be as efficient as using os_log directly. (The README should be updated to mentioned that.)

Also, Swift APIs for os_log is being improved. One of the aims is to align it closely with swift-log. Here are some pointers to the planned unification of os_log and swiftlog levels: https://forums.swift.org/t/logging-levels-for-swifts-server-side-logging-apis-and-new-os-log-apis/20365. Here is the proposal on the redesign of os_log: https://forums.swift.org/t/custom-string-interpolation-and-compile-time-interpretation-applied-to-logging/18799.

**Comment by ktoso** [comment]
That's a good summary @ravikandhadai, thanks (and thanks for the PR)!

I'll close the ticket as that basically answers it, if there's any other questions feel free to reopen though.
