### ISSUE TITLE
Issue setting different levels on log handlers in a MultiplexLogHandler

### ISSUE THREAD

**Issue by ohayon** [apple/swift-log#139]
### Expected behavior
I expected that by setting different levels on the different handlers each one would be respected.

### Actual behavior
Looks like logs are being handled by both handlers only when the log function used is above the levels of *both* handlers.

### Steps to reproduce

In the following code snippet, `MyLogger` sets its own log level to `.info` in its `init` call.

```
    let stdoutLogger: (String) -> StreamLogHandler = { label in
      var logger = StreamLogHandler.standardOutput(label: label)
      logger.logLevel = .trace
      return logger
    }
    LoggingSystem.bootstrap { label in
      return MultiplexLogHandler([MyLogger(), stdoutLogger(label)])
    }

    log.trace("Test Trace")
    log.info("Test Info")
```

The output in the debugger is only:

```
2020-06-25T13:48:21-0400 info: Test Info
```

### SwiftLog version/commit hash
1.2.0

### Swift & OS version (output of `swift --version && uname -a`)
Swift 5.2 on iOS 13.5.1

**Comment by ktoso** [comment]
Interesting catch, thanks for reporting!

So this is a weird interaction between how the `Logger` decides if it should dispatch to the underlying handler or not, it does so by:

```swift
        if self.logLevel <= level {
            self.handler.log(level: level, ...
```


and the multiplex handler naively implements logLevel as:

```swift
    public var logLevel: Logger.Level {
        get {
            return self.handlers[0].logLevel
```

so that's going to yield surprising behaviors as you just noticed.

I think we should be setting the loglevel to the "lowest of any passed in loggers" I suppose.

I'll give this a look since I have a moment now, thanks :-)

**Comment by ohayon** [comment]
Thanks @ktoso ! I just read over the PR comments and that discussion is really great. It seems like a valid workaround for now would be to just reorder the handlers that are being passed into the multiplex handler?

**Comment by ktoso** [comment]
Correct yes, until we land that PR and the behavior changes that's what is documented and the behavior -- so yeah, you can put the "lowest" log level one first and that should work :)

**Comment by ohayon** [comment]
Thanks for the quick reply! 

I think maybe I have misunderstood some of that conversation on the PR, but now, by switching the order of the two loggers, `trace` messages are still getting sent to `MyLogger` which has its log level set to `info`. Is that still expected?

**Comment by ohayon** [comment]
Ah, disregard the last message, sorry! I am seeing now in the code change that that will respect the multiple log levels 😃.
