### ISSUE TITLE
API break in #135 (1.3.0)

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-log#150]
In spite of https://github.com/apple/swift-log/pull/135#issuecomment-647621205, I think the was API actually broken in #135:

This:

```swift
@inlinable
public func debug(_ message: @autoclosure () -> Logger.Message,
                  metadata: @autoclosure () -> Logger.Metadata? = nil,
                  file: String = #file, function: String = #function, line: UInt = #line) {
    ...
}
```

...is not the same as:

```swift
@inlinable
public func debug(_ message: @autoclosure () -> Logger.Message,
                  metadata: @autoclosure () -> Logger.Metadata? = nil,
                  source: @autoclosure () -> String? = nil,
                  file: String = #file, function: String = #function, line: UInt = #line) {
    ...
}
```

We need to retain the old function signatures in addition to the new ones and just forward the implementation from the old to the new.

**Comment by ktoso** [comment]
🔥 🧯 

I see, you're right... eh, what an unlucky release series. Do you want to send in a PR or should I have a look @glbrntt ?

**Comment by glbrntt** [comment]
I should be able to get a patch up today
