### ISSUE TITLE
Add google/swiftlogfirecloud to list of logger backends

### ISSUE THREAD

**Issue by ktoso** [apple/swift-log#156]
A new logger backend to https://firebase.google.com/ ( see https://firebase.google.com/docs/ios/setup )

Thanks a lot @leisurehound for sharing this 🎉 

Would you be able to add it to our list of conforming implementations https://github.com/apple/swift-log#selecting-a-logging-backend-implementation-applications-only ?

If you prefer I add the link let me know, usually we leave it up to the backend authors :)

**Comment by leisurehound** [comment]
Added PR:  https://github.com/apple/swift-log/pull/158

**Comment by ktoso** [comment]
Thanks!
