### ISSUE TITLE
[Question] Is it able to write to file?

### ISSUE THREAD

**Issue by diuming** [apple/swift-log#160]
A simple question.
 Is it able to write to file?

**Comment by ktoso** [comment]
Hi there @diuming,
so this project by itself is really "just API" (and a a minimal stdout/stderr logger), and you should have a look at the other backends which offer more functionality: https://github.com/apple/swift-log#selecting-a-logging-backend-implementation-applications-only

Having that said, I actually don't think we have one in the ecosystem right now which directly writes to a file 🤔 

What you can do is redirect the stdout into a file though with a pipe.

**Comment by diuming** [comment]
@ktoso got it!
