### ISSUE TITLE
Configuring log level

### ISSUE THREAD

**Issue by dscoppelletti** [apple/swift-log#164]
I am using Swift-Log initialized by `LoggingSystem.bootstrap(StreamLogHandler.standardError)`, but on log messages with log level >= `info` are shown on the console window of XCode 12.0.1.  
How can I configure the log level of the log messages shown on the console?  
Thanks.

**Comment by dscoppelletti** [comment]
OK, I figure out:

```
        LoggingSystem.bootstrap { label in
            var handler = StreamLogHandler.standardError(label: label)
            handler.logLevel = Logger.Level.debug
            return handler
        }
```

I would prefer some configuration feature, for example by `label`, but that's it.

**Comment by ktoso** [comment]
Hi @dscoppelletti,
sorry to disappoint but we _really_ only intend swift-log to be the absolute bare minimum package -- that it even ships any log handlers is already pushing it.

As such, we will not be including any "proper log handler" features such as per label configurations or similar.
We hope for the community to step up and implement these features in separate packages shipping more specialized `LogHandler` implementations.

This falls in the same category as https://github.com/apple/swift-log/issues/162 where we unanimously agreed that more features must be kept out of the handlers we shipped and we _must_ encourage more LogHandlers to be implemented.

This of it this way:

- this package is ONLY the API
  - the fact that it ships any log handlers is sadly a historic artifact that we can't remove for now
- any "proper" features should be pushed into LogHandler libraries as much as possible -- we really need to build up an ecosystem or at least a few really good log handlers.

**Comment by ktoso** [comment]
Please report back if this solves your issue and we can close the ticket?

**Comment by dscoppelletti** [comment]
Yeah, it's fair.
