### ISSUE TITLE
A note for the readme

### ISSUE THREAD

**Issue by dpedley** [apple/swift-log#172]
### Expected behavior
package working as a dependency in swift 5.2

### Actual behavior
You get this error:
dependency 'Logging' in target 'BestExampleApp' requires explicit declaration; reference the package in the target dependency with '.product(name: "Logging", package: "swift-log")'

### Steps to reproduce
Following the README doesn't quite work. as the error says, you have to put the package name in with swift 5.2 so from the readme this section would change:

```
.target(name: "BestExampleApp", dependencies: ["Logging"]),
```
^^^ fails, so should become vvv
```
.target(name: "BestExampleApp", dependencies: [.product(name: "Logging", package: "swift-log")]),
```

**Comment by ktoso** [comment]
Thanks, yeah technically we were supporting even 5.1 still -- I think it's good to show in  the readme the 5.2+ version; or perhaps both?

Could you PR that addition?

**Comment by dpedley** [comment]
https://github.com/apple/swift-log/pull/173

**Comment by dpedley** [comment]
Closing, will follow up the PR.
