### ISSUE TITLE
How do I use swiftlog in conjunction with os.log?

### ISSUE THREAD

**Issue by avnerbarr** [apple/swift-log#176]
not sure what is the best practice here. Should I be using os.log or should I be using swift-log?

**Comment by ktoso** [comment]
The best practice is to use os.log directly because going through the swift-log adapters prevents some optimizations and smarts os log is able to perform.

**Comment by ktoso** [comment]
Actually, we have this wording already but perhaps it's not as prominent as it should be:

>  Important Note: we recommend using os_log directly as decribed here. Using os_log through swift-log using this backend will be less efficient and will also prevent specifying the privacy of the message. The backend always uses %{public}@ as the format string and eagerly converts all string interpolations to strings. This has two drawbacks: 1. the static components of the string interpolation would be eagerly copied by the unified logging system, which will result in loss of performance. 2. It makes all messages public, which changes the default privacy policy of os_log, and doesn't allow specifying fine-grained privacy of sections of the message. In a separate on-going work, Swift APIs for os_log are being improved and made to align closely with swift-log APIs. References: Unifying Logging Levels, Making os_log accept string interpolations using compile-time interpretation.
