### ISSUE TITLE
Show Current TheadID and DispatchQueue name

### ISSUE THREAD

**Issue by allright** [apple/swift-log#18]
Example output:
2019-03-19 17:30:21.703 test-log[74560:524592] INF [com.apple.main-thread] [Tag1] > all done with result = true
2019-03-19 17:30:21.699 test-log[74560:524594] INF [com.apple.root.default-qos] [Tag2] > trace from DispatchQueue.global().async {}

This behaviour already implemented here: https://github.com/allright/ASLog/blob/master/ASLog.swift

**Comment by weissi** [comment]
@allright the current `StdoutLogHandler` is not something anyone should use in production. The idea is that swift-log itself is only the API package and there will be an ecosystem around swift-log that implements customisable and production-ready `LogHandler`s. I very much agree with your ask but it should be implemented as a third-party package that ships a swift-log compatible `LogHandler`. You could for example make ASLog a `LogHandler`?

**Comment by allright** [comment]
Yes, I think, I could.

**Comment by allright** [comment]
__dispatch_queue_get_label() - this function return the label of the current dispatch queue on iOS & MacOS.
But we have not this function on Linux :( What function we have to use to get current dispatch queue ?

**Comment by weissi** [comment]
@allright afaik, you can't in Swift. In Swift, calling `__dispatch_queue_get_label` can arbitrarily crash the calling program because it might resurrect an already-dead `DispatchQueue`.

**Comment by weissi** [comment]
@allright if you want a supported way of doing this, please file a Radar (for macOS) and a bugs.swift.org bug against dispatch
