### ISSUE TITLE
should use fwrite not fputs

### ISSUE THREAD

**Issue by weissi** [apple/swift-log#180]
https://github.com/apple/swift-log/blob/12d3a8651d32295794a850307f77407f95b8c881/Sources/Logging/Logging.swift#L828

We should use `fwrite` and not `fputs` here... Usually doesn't matter unless we print a 0 byte which could be a hard to debug thing if we lose everything after the 0 byte with `fputs`.

**Comment by weissi** [comment]
fixed by #188

**Comment by himanshu007-creator** [comment]
Please close this issue
