### ISSUE TITLE
CocoaPods / Carthage support

### ISSUE THREAD

**Issue by larryonoff** [apple/swift-log#19]
Does team consider CocoaPods / Carthage support? I can make PR

**Comment by weissi** [comment]
Sure, why not. But I think we should wait until we tag a version of this (will do soon after Swift 5 gets released).

Does Carthage / CocoaPods have a way of taking the version number from the SwiftPM tags? In SwiftNIO we just build everything with a [script](https://github.com/apple/swift-nio/blob/master/scripts/build_podspecs.sh) so we don't need to check lots of podspecs into our repo.

**Comment by larryonoff** [comment]
@weissi 
> Does Carthage / CocoaPods have a way of taking the version number from the SwiftPM tags?

I don't think that this's supported. So I think SwiftNIO similar scripts is the best option.

**Comment by weissi** [comment]
> @weissi
> 
> > Does Carthage / CocoaPods have a way of taking the version number from the SwiftPM tags?
> 
> I don't think that this's supported. So I think SwiftNIO similar scripts is the best option.

Cool, I'll add a script for CocoaPods when we've tagged a version. It will be much simpler than the SwiftNIO one because we only got one module here so we don't need to figure out the dependencies between the modules.

**Comment by larryonoff** [comment]
@weissi thanks!

**Comment by kimdv** [comment]
Any status on this? 🚀

**Comment by shuoli84** [comment]
bump. Now 1.0.0 released, time for cocoapods?

**Comment by weissi** [comment]
@shuoli84 / @larryonoff does #54 look about right?

**Comment by larryonoff** [comment]
@weissi please see my feedback in PR #54 .

**Comment by weissi** [comment]
the `Logging` pod is now live: https://cocoapods.org/pods/Logging

**Comment by LinusU** [comment]
@weissi is Carthage support something that you are open to adding? We're currently transitioning all our CocoaPods dependencies to Carthage so are hesitant to add new CocoaPods-only deps 😬

**Comment by ianpartridge** [comment]
Xcode 11 supports Swift Package Manager now, is that an option?

**Comment by LinusU** [comment]
Unfortunately, we are actively shipping this app and I don't think that you can submit Xcode 11 compiled apps to the app store until it exits beta.

The next problem is that many of our dependencies don't currently support SwiftPM so we'll probably have to stick with Carthage for a while more, and I would prefer not to mix too many package managers into the mix. The long term goal for is probably CocoaPods -> Carthage -> SwiftPM though, but until we have moved all pods to Carthage I would prefer it not to bring in SwiftPM.

That being said though, long term I 100% think that SwiftPM will solve all of these problems, and I understand if you don't want to support Carthage in the meantime. I would be very happy if you did though ❤️

**Comment by weissi** [comment]
@LinusU I have had someone using NIO with Carthage and it wasn't an issue so I know it works without doing any changes to NIO itself. Let me get some more info for you.

**Comment by schmidan** [comment]
@weissi I (and I would assume many others) would be interested in a way to use swift-log thru carthage. Do you have any more info on this or a short example to point to?
That would be highly appreciated.

**Comment by Bluelich** [comment]
@weissi   Can you update pod spec to 1.5.2, and push it to the trunk. 
Further run the scrip to do this automatically when release a new version？

**Comment by weissi** [comment]
@ktoso / @tomerd / @Lukasa is Cocoapods still supported? I thought that's gone now?

**Comment by ktoso** [comment]
No, you’re right — we don’t support it. Haven’t for a long time I think.
