### ISSUE TITLE
How to push logs to ElasticSearch / ELK server

### ISSUE THREAD

**Issue by muhammadali99** [apple/swift-log#190]
How to push logs to ElasticSearch / ELK server using swift log

**Comment by weissi** [comment]
SwiftLog is only an [API package](https://github.com/apple/swift-log#what-is-an-api-package), to push it to ELK, you could use SwiftLog with an appropriate logging backend. We have a [list](https://github.com/apple/swift-log#selecting-a-logging-backend-implementation-applications-only) of a few logging backends but there may be more out there.

It may also be worth asking on the swift-server Slack if somebody has ideas.

**Comment by muhammadali99** [comment]
Thanks @weissi
