### ISSUE TITLE
Is there a way to bootstrap multiple backends?

### ISSUE THREAD

**Issue by OscarGorog** [apple/swift-log#192]

**Comment by 0xTim** [comment]
No there isn't, there are checks in the code to ensure only one backend is bootstrapped. The way around is to write your own backend that acts as a multiplexer and fans logs out to the different backends

**Comment by ktoso** [comment]
Such multiplex handler exists: https://github.com/apple/swift-log/blob/main/Sources/Logging/Logging.swift#L920

You can bootstrap multiple ones using it like this:

```swift
     LoggingSystem.bootstrap { _ in
            MultiplexLogHandler([logger1, logger2])
        }
```

I'll close the issue but feel free to post follow up questions @OscarGorog !

**Comment by OscarGorog** [comment]
Awesome! Thanks so much for helping!
