### ISSUE TITLE
LogHandler should be provided the calling Logger's label property (or the whole Logger)

### ISSUE THREAD

**Issue by JetForMe** [apple/swift-log#227]
### Expected behavior
LogHandlers should have access to the calling Logger’s `label` property. This is needed so a LogHandler can dynamically control logging from different loggers and families of loggers.

### Actual behavior
This information is not provided in the `log` call, forcing the use of the `metadata` to redundantly carry this information.

### Steps to reproduce

n/a

### If possible, minimal yet complete reproducer code (or URL to code)

n/a

### SwiftLog version/commit hash

1.4.2

### Swift & OS version (output of `swift --version && uname -a`)

n/a

**Comment by JetForMe** [comment]
Oh, perhaps it is, during construction?

**Comment by ktoso** [comment]
Let's focus on the end goal: Would the goal be to enable a log4j style "logger per class" style logging and then to be able to change a log level during runtime for a specific logger by label, I expect?

**Comment by JetForMe** [comment]
That's correct, and it does turn out that the `LogHandler` is provided the label when it is constructed, so it works out.

**Comment by ktoso** [comment]
Of you're working on such backend I'm pretty sure the community would welcome it as well -- if you'd be making it open source :-) Cheers

**Comment by JetForMe** [comment]
Happy to, if I can get it to a point that's generally useful. The other parts I need to add include configurable formatting, and support for multiple types of output (e.g. stdout/console, file, network, etc).

**Comment by tomerd** [comment]
there are some test cases for this kind of functionality: https://github.com/apple/swift-log/blob/main/Tests/LoggingTests/TestLogger.swift#L91 this is of course just a test harness, but it can seed ideas how a "real" logger backend that wants to provide this functionality could be modeled
