### ISSUE TITLE
Crash when using error log / Incomplete LogHandler implementation

### ISSUE THREAD

**Issue by nashysolutions** [apple/swift-log#247]
### Expected behavior
An error log prints in the debugger.

### Actual behavior

- Xcode crash
Firstly: the macOS App runs but does not appear (icon in dock but window not open).
Secondly: CMD+R again to re-run causes Xcode to eventually crash.

<img width="1112" alt="Screenshot 2023-01-09 at 07 14 31" src="https://user-images.githubusercontent.com/64097812/211257144-7268b01f-6412-46e6-bfcc-6d472a46a7ee.png">

### Steps to reproduce

```swift
import Logging

struct Hello: LogHandler {
    
    var metadata: Logging.Logger.Metadata = [:]
    
    var logLevel: Logging.Logger.Level = .error
    
    init(_ label: String) {
    }
    
    public subscript(metadataKey metadataKey: String) -> Logger.Metadata.Value? {
        get {
            return self.metadata[metadataKey]
        }
        set(newValue) {
            self.metadata[metadataKey] = newValue
        }
    }
}
```

```swift
@main
struct TestApp: App {
    
    init() {
        LoggingSystem.bootstrap(Hello.init)
    }
...
}
```

```swift
struct ContentView: View {
        
    var body: some View {
        Text("Hello, World!")
            .onAppear {
                let log = Logger(label: "unique.value")
                log.error("hi")
            }
    }
}
```

### SwiftLog version/commit hash
SHA-1: dc77805fdcb4ebcc5b5897ff99f98e3e518a431d

### Swift & OS version (output of `swift --version && uname -a`)
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
Darwin Roberts-Personal-MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

Xcode Version 14.1 (14B47b)

**Comment by nashysolutions** [comment]
Removing bootstrap fixes the issue

```
// LoggingSystem.bootstrap(Hello.init)
```

**Comment by nashysolutions** [comment]
The documentation states that bootstrap must be called once, else a crash.

Using a singleton resolves this issue.

```swift
final class Client {
    
    static let shared = Hello("Log")
    
    private init() {
        LoggingSystem.bootstrap(Hello.init)
    }
}
```

```swift
@main
struct TestApp: App {
    
    init() {
        _ = Client.shared
//        LoggingSystem.bootstrap(Hello.init)
    }
```

It might be worth adding some code to display a clear error message for this.

**Comment by ktoso** [comment]
This is the same as https://github.com/apple/swift-log/issues/248 isn't it?

Your LogHandler implementation is incomplete, you _must_ implement a `log` method for it to work; Please check https://github.com/apple/swift-log/issues/248 for details.
