### ISSUE TITLE
Infinite recursion between deprecated API's

### ISSUE THREAD

**Issue by nashysolutions** [apple/swift-log#248]
### Expected behavior
Print log to debugger

### Actual behavior

<img width="424" alt="Screenshot 2023-01-09 at 07 41 06" src="https://user-images.githubusercontent.com/64097812/211262002-ff4f62b3-a3d6-4f8b-9b97-34ffb819fd5d.png">

<img width="877" alt="Screenshot 2023-01-09 at 07 41 16" src="https://user-images.githubusercontent.com/64097812/211262014-392e3313-b72e-43a9-957e-cfe5307efd16.png">

### Steps to reproduce

```swift
import Logging

struct Hello: LogHandler {
    
    var metadata: Logging.Logger.Metadata = [:]
    
    var logLevel: Logging.Logger.Level = .error
    
    init(_ label: String) {
    }
    
    subscript(metadataKey metadataKey: String) -> Logger.Metadata.Value? {
        get {
            return self.metadata[metadataKey]
        }
        set(newValue) {
            self.metadata[metadataKey] = newValue
        }
    }
}
```

```swift
import Logging

final class Client {
    
    static let shared = Client()
    
    private init() {
        LoggingSystem.bootstrap(Hello.init)
    }
}

@main
struct TestApp: App {
    
    init() {
        _ = Client.shared
    }
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

```swift
import Logging

struct ContentView: View {
    
    init() {
        var log = Logger(label: "unique.value")
        log[metadataKey: "mykey"] = "jelly"
        log.error("hi")
    }
        
    var body: some View {
        Text("Hello, World!")
    }
}
```

The `init` for SwiftUI view's may be called multiple times, but this doesn't seem to be the issue.

### SwiftLog version/commit hash
Latest release as of (9th Jan 2023) - v1.4.4

### Swift & OS version (output of `swift --version && uname -a`)
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
Darwin Roberts-Personal-MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

Xcode Version 14.1 (14B47b)

**Comment by ktoso** [comment]
You didn't finish implementing your log handler, in the screenshot you paste the solution is included:

```
    @available(*, deprecated, message: "You should implement this method instead of using the default implementation")
    public func log(level: Logger.Level,
                    message: Logger.Message,
                    metadata: Logger.Metadata?,
                    source: String,
                    file: String,
                    function: String,
                    line: UInt) {
// ... 
    }
```


you have to implement this method. It delegates to old methods for compatibility with existing LogHandler implementations which used the "old" API. This way we did not break source compat when adding the new handler APIs.

Please implement the above method and things will work as expected.

**Comment by ktoso** [comment]
Double checked, yeah this works correctly:

```swift
import Logging

@main
public struct untitled4 {

    public static func main() {
        LoggingSystem.bootstrap(Hello.init)

        var log = Logger(label: "unique.value")
        log[metadataKey: "mykey"] = "jelly"
        log.error("hi")
    }
}

struct Hello: LogHandler {

    var metadata: Logging.Logger.Metadata = [:]

    var logLevel: Logging.Logger.Level = .error

    init(_ label: String) {
    }

    subscript(metadataKey metadataKey: String) -> Logger.Metadata.Value? {
        get {
            return self.metadata[metadataKey]
        }
        set(newValue) {
            self.metadata[metadataKey] = newValue
        }
    }

    // REQUIRED
     func log(level: Logger.Level,
                    message: Logger.Message,
                    metadata: Logger.Metadata?,
                    source: String,
                    file: String,
                    function: String,
                    line: UInt) {
        print("message: \(message)")
    }
}
```

Please complete your LogHandler implementation and it'll work fine. 
If there's anything else here please feel free to comment or reopen the issue

**Comment by nashysolutions** [comment]
Please re-open this ticket :) I will submit a PR to fix.

**Comment by ktoso** [comment]
Commented more in the PR: https://github.com/apple/swift-log/pull/249
We can't do source breaking changes like this for quite a while.
