### ISSUE TITLE
Add new Discord Logger to README

### ISSUE THREAD

**Issue by MahdiBM** [apple/swift-log#256]
### Discord Logger

 * I've recently publicized the Discord-logger part of the private Discord stuff I'm using.

* For what it's worth, I've personally moved to the publicized version of the logger since a few days ago, and everything has been going smoothly. 

* We're soon going to use the logger in [Vapor community's Penny](https://github.com/vapor/penny-bot/pull/39). 

* The logger also has a [decent amount of tests](https://github.com/MahdiBM/DiscordBM/blob/main/Tests/DiscordBMTests/DiscordLogger.swift).

* It does take care of edge cases. For example, the logger:
  * Won't exceed Discord message-length limits. Will try to truncate if possible.
  * Won't exceed its Discord rate-limit when sending logs.
  * Will escape Discord-special characters before sending over to Discord.
 
  And much more ...
  
If you need to review the implementation, the logger-related parts of the library are present in the [DiscordLogger](https://github.com/MahdiBM/DiscordBM/tree/main/Sources/DiscordLogger) target and there is a [Discord-logger section available in the README](https://github.com/MahdiBM/DiscordBM/blob/discord-logger/README.md#discord-logger).

**Comment by ktoso** [comment]
Hm, it's not really a stand-alone logger package... but I guess for discord that would be perhaps weird to begin with.

I don't mind adding a link to it :) I see you're handling metadata providers nicely even 👍

**Comment by MahdiBM** [comment]
Yeah its not standalone, and I did think of that. That's why you can only depend on `DiscordLogger` instead of the whole `DiscordBM`.
It will still pull more stuff than a standalone logger package would, but I think it should be fine.
