### ISSUE TITLE
Make `StdioOutputStream` public

### ISSUE THREAD

**Issue by fumoboy007** [apple/swift-log#260]
Thanks for creating and maintaining `StdioOutputStream`! It looks like a generally useful API for writing to standard output or standard error.

Would y’all be willing to make the API public—either in this package, or in a separate package that is perhaps also Apple-owned?

**Comment by ktoso** [comment]
Personally I don't think we'd want to offer such package, but perhaps we could see if something in swift-system or swift's "new foundation" (written in swift) could take this on. 

Would you want to pitch the idea on the forums? http://forums.swift.org

License wise feel free to make such package with the type but I don't think we should jump the shark 🦈 to standardize it while we have a chance to put standard types for this in a potentially more "core" location.
