### ISSUE TITLE
Elastic common schema

### ISSUE THREAD

**Issue by wibed** [apple/swift-log#332]
https://www.elastic.co/guide/en/ecs/current/ecs-reference.html defines how log and metrics data should look like adapted to distributed requirements.

would it be feasible to include this for swift-log?

```
it seems to me that:
- https://github.com/apple/swift-distributed-tracing
- https://github.com/apple/swift-metrics
- https://github.com/apple/swift-log

try to tackle the same goal. therewhile a common baseline and the ability to spawn different types of handlers off of it would be awesome from a ux perspective. 
if these could be combined on top of any distributed actor system, handling the surface of actors spawned that way. that would be even better.
```
 my 2 cents

**Comment by 0xTim** [comment]
It's up to the individual handler how the logs should be formatted, e.g. https://github.com/rwbutler/swift-log-ecs
