### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by lhoward** [apple/swift-log#335]
Would be great to have a release for those of us building against Android, so we don't have build depend on a branch.

**Comment by lhoward** [comment]
Also WIP: https://github.com/PADL/AndroidLogging

**Comment by ktoso** [comment]
This just asks for a release of current main right? We can do that, no problem.

**Comment by ktoso** [comment]
Since it'll have https://github.com/apple/swift-log/commit/d03205626d4616d00eabdc0ea2b93bac08b1a30f

**Comment by lhoward** [comment]
Yes, I'm just asking for a tagged release of swift-log with Android support.

**Comment by glbrntt** [comment]
Sorry about the delay here – we just released https://github.com/apple/swift-log/releases/tag/1.6.2
