### ISSUE TITLE
add color feature?

### ISSUE THREAD

**Issue by iOSleep** [apple/swift-log#34]
Long long ago, Xcode console was colorful by plug-ins.
![colorful console](https://raw.githubusercontent.com/DaveWoodCom/XCGLogger/master/ReadMeImages/SampleLog.png)
Now Xcode not support it, we use ANSI format and other software to look up the log like terminal. [detail](https://github.com/DaveWoodCom/XCGLogger#enhancing-log-messages-with-colour)

it's time to change it
best wishes

**Comment by weissi** [comment]
Thanks, but`swift-log` is an API package only.

Colours are super useful but they should be implemented as a `swift-log`-compatible logging backend, a `LogHandler`.

That way all `swift-log` users can use this.
