### ISSUE TITLE
Countdown to 1.0.0

### ISSUE THREAD

**Issue by weissi** [apple/swift-log#38]
I'm intending to cut `1.0.0` (and `0.1.0` for Swift 4.2 support) tonight 2019-04-09 (GMT).

The intended meaning of `1.0.0` is:
- we now follow SemVer 2.0.0
- you can now start depending on this package

and nothing else :)

**Comment by weissi** [comment]
CC @tomerd / @ianpartridge / @tanner0101 / @ktoso

**Comment by ktoso** [comment]
:shipit:

**Comment by ianpartridge** [comment]
🥇

**Comment by tomerd** [comment]
:doit:

**Comment by weissi** [comment]
done
