### ISSUE TITLE
Should StdoutLogHandler include label in log output?

### ISSUE THREAD

**Issue by ktoso** [apple/swift-log#57]
### Expected behavior

When logging using different loggers, e.g.:

```
let one = Logger(label: "one")
let two = Logger(label: "two")
```

I would expect the labels `one` and `two` to appear in log output.
This is not the case with the default `StdoutLogHandler`:

```swift
internal struct StdoutLogHandler: LogHandler {
    private let lock = Lock()

    public init(label: String) {} // does not store label
```

I know the StdOutLogHandler is meant to be _super minimal_ but this seems more like an omission?

### Actual behavior

Label is not included in log statements logged through to default std out handler.

**Comment by weissi** [comment]
I would say it should not because I don't think that's what people really expect. Most logging systems don't actually force you to provide a label. I think the label is useful but we shouldn't force it on users. If they want it, as usually my answer would be 'make you own `LogHandler`' MYOLH ;)

**Comment by ianpartridge** [comment]
I think logging to stdout/stderr is really common, people will expect it to work out of the box, and if we're shipping such a `LogHandler` (and I think we should) we should make it super awesome.

**Comment by weissi** [comment]
> I think logging to stdout/stderr is really common, people will expect it to work out of the box, and if we're shipping such a `LogHandler` (and I think we should) we should make it super awesome.

Hmm, but this is deliberately just an API package because if we try to make it even 'maybe awesome' people will have conflicting opinions in what that means. So by shipping something barebones, literally that there is some output is I believe better. 

Sure, for right now, where there's not many backend implementations it's a bit rough but I think that'll sort itself out :)

**Comment by kirilltitov** [comment]
In my custom LogHandler I print `label` only if `logLevel` is `debug` or `trace`. But I'm not entirely sure `StdoutLogHandler` should utilize this logic, it's not that obvious for a random user :)

**Comment by weissi** [comment]
> In my custom LogHandler I print `label` only if `logLevel` is `debug` or `trace`. But I'm not entirely sure `StdoutLogHandler` should utilize this logic, it's not that obvious for a random user :)

Yes, agreed.

**Comment by ktoso** [comment]
> I would say it should not because I don't think that's what people really expect. Most logging systems don't actually force you to provide a label. I think the label is useful but we shouldn't force it on users. 

API wise we _do_ force it though, so I thought it is weird that we do force passing a label, but it never appears anywhere; printout wise if the label passed in is empty -- there's also no printout of it, so I don't think it changes the printing semantics if it was printed?

> If they want it, as usually my answer would be 'bring you own LogHandler' BYOL(H) ;).

That's probably fair; I rely a lot on loggers during library development and have some needs for them -- so might as well just implement my own that "one should never use"™ other than when I run my tests etc, since I need logging there.

**Comment by shpakovski** [comment]
Having a label would help to filter out particular logs, without introducing your own handler. As Konrad said, if you provide a label, it *should* be useful. As a user, I’d expect such behavior. Thanks!

**Comment by ultraon** [comment]
Hey guys, I've created convenience way to create a logger and use a label, see https://gist.github.com/ultraon/2659f1c6c8885e8d8dc47d45b9187449

Finally, I use it in this way: `private let LOG = logger("MyTag")`,
and then in the same file: `LOG.debug("my message)`,
output: `2019-12-15T22:02:26+0200 debug: MyTag: my message`
