### ISSUE TITLE
iOS Compatibility issues

### ISSUE THREAD

**Issue by prafsoni** [apple/swift-log#79]
I recently adopted `swift-log`. Now `pod lib lint` is failing with the following error.
```
import Logging
           ^
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CompileSwift normal i386
    	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
    (2 failures)
```
Is `swift-log` only for server-side use? I believe this should be available on all platforms where swift is available may be as part of `core-libs`.

### SwiftLog version

`1.1.0`

### Swift & OS version (output of `swift --version && uname -a`)
```
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.6.0
Darwin Prafulls-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

**Comment by weissi** [comment]
It should definitely work on iOS. Where do you run the `pod lib lint` ? @tkrajacic aren't you using SwiftLog on iOS?

**Comment by tkrajacic** [comment]
I am not using Cocoapods but including the SPM package’s Xcode project as a sub-project.
That works reasonably well.

**Comment by weissi** [comment]
Thanks @tkrajacic . Let's try @pyrtsa or @larryonoff who I think are using the Pod.

**Comment by prafsoni** [comment]
@weissi I am using SwiftLog in [ElastcSwift](https://github.com/pksprojects/ElasticSwift/tree/feature/modules ) I have added SwiftLog as SPM dependency. I am getting this error when validating ElasticSwift.podspec. I believe it’s not able to resolve SwiftLog also I don’t see SwiftLog pod in Cocoapods

**Comment by weissi** [comment]
@prafsoni I'm not sure if I can follow. You said you added `SwiftLog` as an SwiftPM dependency, why is it then also added as a Cocoapod?

**Comment by prafsoni** [comment]
@weissi ElasticSwift is developed as SPM library package. However, ElasticSwift is also available as a pod. I am getting this error while packaging ElasticSwift as a pod. I think it’s just packaging issue on my side and not an iOS compatibility. I believe just need SwiftLog pod to solve my issue. Also can you point me to official pod I am not able to find it.

**Comment by prafsoni** [comment]
found it official pod got confused due to open pull request #20 apologies for misleading issue closing it.

**Comment by larryonoff** [comment]
@weissi thanks for mentioning me. Unfortunately I don't use swift-log in my projects at the moment. Just FYI build output is too short to find out the issue.

**Comment by weissi** [comment]
Cool, thanks @prafsoni. For anybody else reading this, the pod is https://cocoapods.org/pods/Logging (pod name `Logging` because `SwiftLog` was taken).
